### ISSUE TITLE
Drools: Fix smoke test

### ISSUE THREAD

**Issue by apodhrad** [jbosstools/jbosstools-integration-stack-tests#350]
The test fails on winos7_64, see the error

Error Message

Unexpected text in console
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Hello World
Goodbye cruel world

Stacktrace

java.lang.AssertionError: Unexpected text in console
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Hello World
Goodbye cruel world

	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.jboss.tools.drools.ui.bot.test.functional.DefaultRuntimeTest.testRunRulesWithDefaultRuntime(DefaultRuntimeTest.java:55)

**Comment by apodhrad** [comment]
![002-org jboss tools drools ui bot test functional defaultruntimetest-testrunruleswithdefaultruntimedrools-620final xml](https://cloud.githubusercontent.com/assets/2270674/7605508/a4044988-f950-11e4-854b-1c75f47331e9.png)

**Comment by apodhrad** [comment]
@tomasdavidorg could you have a look at it, please?

**Comment by tomasdavidorg** [comment]
ok

**Comment by tomasdavidorg** [comment]
fixed by #352
