### ISSUE TITLE
BPMN2: Use SOA Requirements

### ISSUE THREAD

**Issue by apodhrad** [jbosstools/jbosstools-integration-stack-tests#568]
@jomarko could you have a look at it, please?

**Comment by apodhrad** [comment]
Btw, what's the purpose of the followin setting?
-Dgraphiti.properties=true

**Comment by domhanak** [comment]
Found this explanation @apodhrad 
> -Dgraphiti.properties=[bool] - optional argument, determines if properties of elements are handled by Properties view[false] or Graphiti popup dialogs[true]

**Comment by jomarko** [comment]
properties of process elements (task, gateway, event) can be set in two ways.
* First way is in the properties panel shown in the bottom of the screen
* Second way is in popup shown directly to the selected process element. The popup ws implemented by some graphiti library, that is where the property name comes from.

**Comment by apodhrad** [comment]
Closed as outdated
