### ISSUE TITLE
Fuse: Add tests for Invalid XML file handling

### ISSUE THREAD

**Issue by apupier** [jbosstools/jbosstools-integration-stack-tests#598]
There was several bugs reported which handled to data loss when an xml file modified by hand and if no data loss, at least it was messed up and user has no information to solve the issue.

It will be nice to have UI tests about the following usecases:
- Opening of an invalid XML file and switch between Design/Source/configuration editor tabs see https://issues.jboss.org/browse/FUSETOOLS-1608 for instance
- Opening a valid Camel context file, go to Source and modify it to be invalid, switch to other tabs
- add yours...

**Comment by tsedmik** [comment]
Moved to another ITS - https://issues.jboss.org/browse/JBTIS-756
